### ISSUE TITLE
Unable to access conceptarium via the API

### ISSUE THREAD

**Issue by phkus** [paulbricman/conceptarium#10]
I've installed it via Docker and entered a token at localhost:8501. But I can't access it through the Curl or Request URL provided in the docs. Check custodian results in "{"custodian":false,"authorized_microverse":[]} and /save in "Only the conceptarium's custodian can save thoughts in it."

One thing that came to mind: I've used special characters in the token. Could the issue be with the URL encoding?

**Comment by paulbricman** [comment]
Hm, could you try:

```
docker container ls
docker exec -i -t <backend container id> /bin/bash
cd /app
cat records.json
```

This should print the contents of the records file, including the custodian token (it's plaintext because if you've got access to the file system, you could get the thoughts anyway). We'll see whether the right token made it there in the first place, and debug from there.

**Comment by phkus** [comment]
Looks like my token didn't get registered, it shows me a different one.

Just to make sure I didn't make a mistake at the beginning: The way I set a token after installation is simply by entering it in the token field below "connect to new microverse" the first time I log in, right?

**Comment by paulbricman** [comment]
> The way I set a token after installation is simply by entering it in the token field below "connect to new microverse" the first time I log in, right?

Yeah, that should be it!

> Looks like my token didn't get registered, it shows me a different one.

Oh no, is it a completely unrelated one? Or a messed up version due to some special characters?

**Comment by phkus** [comment]
No it's completely different.

**Comment by paulbricman** [comment]
Yeah, sure! I'm wondering whether one I used at some point slipped in due to some poor .gitignore rules, but let's have a look.

**Comment by paulbricman** [comment]
@phkus Could you please try removing your local Docker images and trying to docker-compose the latest ones? I made it so that the records.json file which contains the "master" custodian token is stored in the mounted knowledge folder, rather than among the source files.

**Comment by phkus** [comment]
That worked, I'm now the custodian. Thanks for your help!
