### ISSUE TITLE
Where is the access token?

### ISSUE THREAD

**Issue by micole66** [paulbricman/conceptarium#14]

**Comment by paulbricman** [comment]
Thanks for the interest. First, I pushed a relevant update to the Docker images just now, make sure to fetch the latest, see #10.

The first token you use on a fresh instance becomes the "master" token, which gives you full read/write access to the stored thoughts. With this last update, it should be stored in `knowledge/records.json`. Does that make sense, @micole66?

**Comment by paulbricman** [comment]
And the autogenerated docs for the API now also indicate that each endpoint needs the token: 

![image](https://user-images.githubusercontent.com/20104026/153864758-8db2a62f-ce05-42fc-acb0-f314a7674ef3.png)

Let me know if you're still looking into this :)
