### ISSUE TITLE
Online demo instance showing error - No such file or directory: components

### ISSUE THREAD

**Issue by NumesSanguis** [paulbricman/conceptarium#21]
Your [online instance hosted on Hugging Face](https://huggingface.co/spaces/paulbricman/conceptarium) is currently facing an issue, the one you link from [your blog](https://paulbricman.com/thoughtware/conceptarium):
```python
FileNotFoundError: [Errno 2] No such file or directory: 'components'
Traceback:

File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/frontend/main.py", line 12, in <module>
    microverses.paint()
File "frontend/components/microverses.py", line 24, in paint
    components = [e.split('.')[0] for e in os.listdir('components') if e.endswith(
```

-----
Unrelated, but thank you for the interesting write-ups!

**Comment by paulbricman** [comment]
Thanks for the find, @NumesSanguis, it should be solved now. Let me know if you run into other issues, feedback right now is super valuable!
