### ISSUE TITLE
probem with Docker installation

### ISSUE THREAD

**Issue by phkus** [paulbricman/conceptarium#9]
I've installed the new version of the conceptarium on MacOS following the Docker approach. During the installation there were no errors, but now I cannot get the Docker image to run.

The frontend image exits immediately after starting it, with the following error in the log:
Error: Invalid value: File does not exist: main.py
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

The backend image does show as "Running", but looking at the log there is also an error:
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8] using watchgod
ERROR:    Error loading ASGI app. Could not import module "main".

**Comment by paulbricman** [comment]
Thanks for putting together the issue, @phkus! Could you please have a look at the updated instructions?
